version: '3.9'

services:
  db:
    image: postgres
    networks:
      lab-monitoring-network:
        ipv4_address: 10.5.0.2
    restart: always
    ports:
      - 5432:5432    
    shm_size: 128mb    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "472:472"  # Run as the Grafana user
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "123456"
    volumes:
      - grafana_lab_data:/var/lib/grafana
    networks:
      lab-monitoring-network:
        ipv4_address: 10.5.0.3
    restart: always
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      lab-monitoring-network:
        ipv4_address: 10.5.0.4

  jaeger:
    image: jaegertracing/jaeger:2.2.0
    container_name: jaeger    
    ports:
      - "16686:16686" # the jaeger UI 
      - "4317:4317" # the OpenTelemetry collector grpc 
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      lab-monitoring-network:
        ipv4_address: 10.5.0.5
    restart: always

  # api products
  ms-spring-product-api:
    image: img-ms-spring-product-api
    ports:
      - "8001:8001"
    networks:
      lab-monitoring-network:
        ipv4_address: 10.5.0.6

  # api products client
  ms-spring-product-client-api:
    image: img-ms-spring-product-client-api
    ports:
      - "7001:7001"
    networks:
      lab-monitoring-network:
        ipv4_address: 10.5.0.7

networks:
  lab-monitoring-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

volumes:
  grafana_lab_data:
